[package]
name = "tg-public-log-parser"
authors = ["Mothblocks"]
version = "1.0.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
regex = "1.11.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-tracy = { version = "0.11.4", optional = true }

[features]
tracy = ["tracing-tracy"]
